#!/bin/sh

#setup repository

sudo apt update -y
echo ****************UPDATE COMPLETE****************

sudo apt upgrade -y
echo ****************UPGRADE COMPLETE****************

curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
echo ****************CURL COMPLETE****************

sudo apt-key fingerprint 0EBFCD88
echo ****************KEY ADDED****************

sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
echo ****************REPO ADDED****************
#install docker

#update repo
sudo apt update -y
echo ****************UPDATE COMPLETE****************
#check fetch to docker.com
apt-cache policy docker-ce
echo ****************CACHE COMPLETE****************

sudo apt-get install -y docker-ce
echo ****************INSTALL COMPLETE****************

#check status
sudo systemctl status docker
echo ****************DOCKER STATUS****************

#looking for docker.service active
